const contractAddress = "0x9a69a9F0FcFbDE120D1551f4d0150914237D2F2F"; // Replace with your own contract address
const chain = 'polygon'; // goerli, polygon, or ethereum

const welcome_h1 = "Rath NFTs";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Rath-the NFT collection has been created in the memory of the classic cartoon series "BEN 10". The collection is based on one of the characters, the Rath , an appoplexian hitting the polygon blockchain.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale..";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! ";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you!";
const p_public_mint = "No whitelist needed. Public minting is now open!";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. Please try again.";
